# filecoin-service - Example configuration file# https://documenter.getpostman.com/view/4872192/SWLh5mUd?version=latest

[remote_node]
url = "http://127.0.0.1:1234/rpc/v0"
jwt = ""

[service]
address = "127.0.0.1:3030"
