version: 2.1

commands:
  restore-sccache-cache:
    steps:
      - restore_cache:
          name: Restore sccache cache
          key: sccache-cache-stable-{{ arch }}
#          key: sccache-cache-stable-{{ arch }}-{{ .Environment.CIRCLE_JOB }}
  save-sccache-cache:
    steps:
      - save_cache:
          name: Save sccache cache
#          key: sccache-cache-stable-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ epoch }}
          key: sccache-cache-stable-{{ arch }}-{{ epoch }}
          paths:
            - "~/.cache/sccache"

jobs:
  build:
    docker:
      - image: zondax/rust-ci:latest
    steps:
      - checkout
      - restore-sccache-cache
      - run: sudo apt-get update -y && sudo apt-get install -y libusb-1.0.0 libudev-dev
      - run:
          name: rustfmt
          command: |
            cargo fmt --version
            cargo fmt -- --check
      - run:
          name: clippy
          command: |
            cargo clippy --version
            cargo clippy --all-features --all-targets
      - run:
          name: audit
          command: |
            cargo audit --version
            cargo audit
      - save-sccache-cache

  tests_rust:
    docker:
      - image: zondax/rust-ci:latest
    steps:
      - checkout
      - restore-sccache-cache
      - run: sudo apt-get update -y && sudo apt-get install -y libusb-1.0.0 libudev-dev
      - run:
          name: rust unit tests --all-features
          command: |
            rustc --version
            cargo --version
            cargo test --lib --all-features
      # No need to save this in cache

  tests_ffi:
    docker:
      - image: zondax/rust-ci:latest
    steps:
      - checkout
      - restore-sccache-cache
      - run:
          name: External dependencies
          command: |
            sudo apt-get install -y clang default-jdk g++ gcc gnustep gnustep-devel gobjc golang libicu-dev libtinfo5 valgrind
      - run:
          name: Cbindgen
          command: |
            cd signer-ffi
            rustup install nightly
            rustup default nightly
            cargo install cbindgen
            cbindgen --config cbindgen.toml --crate filecoin-signer-ffi --lang c --output /tmp/filecoin_signer_ffi.h
            cbindgen --config cbindgen.toml --crate filecoin-signer-ffi --lang c++ --output /tmp/filecoin_signer_ffi_cpp.h
      - run:
          name: Libraries
          command: |
            cd signer-ffi
            cargo build
            cp ../target/debug/libfilecoin_signer_ffi.so /tmp/libfilecoin_signer_ffi.so
            cargo build --features with-jni
            cp ../target/debug/libfilecoin_signer_ffi.so /tmp/libfilecoin_signer_ffi_java.so
      - run: OUT_DIR=/tmp/c ./.circleci/test_c.sh
      - run: OUT_DIR=/tmp/cpp ./.circleci/test_cpp.sh
      - run: OUT_DIR=/tmp/go ./.circleci/test_go.sh
      - run: OUT_DIR=/tmp/java ./.circleci/test_java.sh
      - run: OUT_DIR=/tmp/kotlin ./.circleci/test_kotlin.sh
      - run: OUT_DIR=/tmp/objective-c ./.circleci/test_objective-c.sh
      - run: OUT_DIR=/tmp/swift ./.circleci/test_swift.sh

  tests_npm:
    docker:
      - image: zondax/rust-ci:latest
    steps:
      - checkout
      - run: cargo --version
      - restore-sccache-cache
      - run: sudo apt-get update && sudo apt-get install -y firefox-esr libnss3
      - run: make install_wasmpack SILENT=true
      # Disabling Chrome (only Firefox) due to  https://github.com/Zondax/filecoin-signing-tools/issues/68
      - run: make test_npm_unit
      - run: make test_npm_node
      - save-sccache-cache
      # No need to save this in cache

  tests_ledger:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    environment:
      BASH_ENV: "/opt/circleci/.nvm/nvm.sh"
    steps:
      - restore-sccache-cache
      - run: sudo apt-get update -y && sudo apt-get install -y libusb-1.0.0 libudev-dev curl
      - run:
          name: Install rustup
          command: |
            curl https://sh.rustup.rs -o rustup.sh
            chmod +x rustup.sh
            ./rustup.sh -y
            source $HOME/.cargo/env
            rm rustup.sh
      - checkout
      - run: git submodule update --init --recursive
      - run: docker pull zondax/builder-zemu
      - run:
          name: Install node + yarn
          command: |
            nvm install 14.4.0
            nvm use 14.4.0
            npm install -g yarn
      - run:
          name: Install deps wasm
          command: |
            source $HOME/.cargo/env
            nvm use 14.4.0
            make install_wasmpack SILENT=true
      - run:
          name: Run zemu tests
          command: |
            nvm use 14.4.0
            source $HOME/.cargo/env
            make test_ledger
      - save-sccache-cache

  tests_service:
    docker:
      - image: zondax/rust-ci:latest
#    environment:
#      LOTUS_SECRET_URL: some_url
#      LOTUS_SECRET_JWT: some_jwt
    steps:
      - checkout
      - restore-sccache-cache

      - run: cargo build --manifest-path service/Cargo.toml
      - run:
          name: patch configuration file
          command: |
            echo [service] >> filecoin-service.toml
            echo address = \"127.0.0.1:3030\" >> filecoin-service.toml
            echo [remote_node] >> filecoin-service.toml
            echo url = \"$LOTUS_SECRET_URL\" >> filecoin-service.toml
            echo jwt = \"$LOTUS_SECRET_JWT\" >> filecoin-service.toml
      - run:
          name: start service
          background: true
          command: |
            cargo run --manifest-path service/Cargo.toml -- start
      - run:
          name: install node dependencies
          command: |
            cd examples/service_jsonrpc
            yarn install
      - run:
          name: wait for service to be available
          command: .circleci/wait_for_port.sh 3030
      - run:
          name: run jsonrpc tests
          command: |
            cd examples/service_jsonrpc
            yarn run test:unit
            yarn run test:integration
      # No need to save this in cache

  npm_publish:
    docker:
      - image: zondax/rust-ci:latest
    steps:
      - checkout
      - restore-sccache-cache
      - run: make install_wasmpack SILENT=true
      - run: make build_npm
      - run:
          name: Update tag
          command: |
            cd /home/circleci/project/signer-npm/pkg
            echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
            npm --no-git-tag-version version $CIRCLE_TAG
            npm publish

  rust_publish:
    docker:
      - image: zondax/rust-ci:latest
    steps:
      - checkout
      - restore-sccache-cache
      # TODO: Enable cargo publish

no-tags: &no-tags
  filters:
    tags:
      ignore: /.*/

only-release-tags: &only-release-tags
  filters:
    tags:
      only: /^v[0-9]+(\.[0-9]+)*(-[a-z]+)?$/
    branches:
      ignore: /.*/

workflows:
  version: 2

  default:
    jobs:
      - build:
          <<: *no-tags
      - tests_rust:
          <<: *no-tags
      - tests_npm:
          <<: *no-tags
      - tests_ffi:
          <<: *no-tags
      - tests_service:
          <<: *no-tags
      - tests_ledger:
          <<: *no-tags

  release:
    jobs:
      - build:
          <<: *only-release-tags
      - tests_rust:
          <<: *only-release-tags
      - tests_ffi:
          <<: *only-release-tags
      - tests_npm:
          <<: *only-release-tags
      - tests_service:
          <<: *only-release-tags
      - tests_ledger:
          <<: *only-release-tags

#      - rust_publish:
#          <<: *only-release-tags
#          requires:
#            - build
#            - tests_rust
#            - tests_npm
#            - tests_service

      - npm_publish:
          <<: *only-release-tags
          requires:
            - build
            - tests_rust
            - tests_npm
            - tests_service
            - tests_ledger
